// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    public partial class PurchaseArticles
    {
        public PurchaseArticles()
        {
            Quotes = new HashSet<Quotes>();
            RequisitionArticles = new HashSet<RequisitionArticles>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }
        [Required]
        [StringLength(20)]
        public string Unit { get; set; }
        [StringLength(50)]
        public string TradeMark { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        public int FamilyId { get; set; }
        [Required]
        [StringLength(20)]
        public string Code { get; set; }

        [ForeignKey(nameof(FamilyId))]
        [InverseProperty(nameof(ArticleFamilies.PurchaseArticles))]
        public virtual ArticleFamilies Family { get; set; }
        [InverseProperty("Article")]
        public virtual ICollection<Quotes> Quotes { get; set; }
        [InverseProperty("Article")]
        public virtual ICollection<RequisitionArticles> RequisitionArticles { get; set; }
    }
}