// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Index(nameof(Id), Name = "IX_Requisitions", IsUnique = true)]
    public partial class Requisitions
    {
        public Requisitions()
        {
            PurchaseOrders = new HashSet<PurchaseOrders>();
            RequisitionArticles = new HashSet<RequisitionArticles>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string RequisitionNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? IssuedDate { get; set; }
        [Required]
        [StringLength(450)]
        public string UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RequiredDate { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(AspNetUsers.Requisitions))]
        public virtual AspNetUsers User { get; set; }
        [InverseProperty("Requisition")]
        public virtual ICollection<PurchaseOrders> PurchaseOrders { get; set; }
        [InverseProperty("Requisition")]
        public virtual ICollection<RequisitionArticles> RequisitionArticles { get; set; }
    }
}