// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Entities
{
    [Index(nameof(RoleId), Name = "IX_SystemRolePermissions", IsUnique = true)]
    public partial class SystemRolePermissions
    {
        [Required]
        public string RoleId { get; set; }
        [Required]
        public string PermissionValue { get; set; }
        [Key]
        public int Id { get; set; }

        [ForeignKey(nameof(RoleId))]
        [InverseProperty(nameof(AspNetRoles.SystemRolePermissions))]
        public virtual AspNetRoles Role { get; set; }
    }
}