// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Index(nameof(GroupId), Name = "FK_ArticleFamilies_ArticleGroups")]
    public partial class ArticleFamilies
    {
        public ArticleFamilies()
        {
            PurchaseArticles = new HashSet<PurchaseArticles>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }
        [Required]
        [StringLength(20)]
        public string Code { get; set; }
        public int GroupId { get; set; }

        [ForeignKey(nameof(GroupId))]
        [InverseProperty(nameof(ArticleGroups.ArticleFamilies))]
        public virtual ArticleGroups Group { get; set; }
        [InverseProperty("Family")]
        public virtual ICollection<PurchaseArticles> PurchaseArticles { get; set; }
    }
}