// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class AssociatedContactsView
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string FullName { get; set; }
        [Required]
        [StringLength(50)]
        public string EmailAddress { get; set; }
        [Required]
        [StringLength(20)]
        public string MobilePhone { get; set; }
        [StringLength(50)]
        public string Position { get; set; }
        [Required]
        [StringLength(14)]
        public string CompanyId { get; set; }
        [Required]
        [StringLength(8)]
        public string Status { get; set; }
    }
}