// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class HistoryView
    {
        public int Id { get; set; }
        [StringLength(20)]
        public string Action { get; set; }
        [StringLength(50)]
        public string TableName { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        [Required]
        [StringLength(450)]
        public string UserRoleId { get; set; }
        [StringLength(256)]
        public string UserRoleName { get; set; }
        [Required]
        [StringLength(101)]
        public string PersonShortName { get; set; }
        [Required]
        [StringLength(203)]
        public string PersonFullName { get; set; }
        public DateTime? TimeOfAction { get; set; }
    }
}