// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class ProjectProductsView
    {
        public int ProductId { get; set; }
        public int ProjectId { get; set; }
        public float SalePrice { get; set; }
        public int Quantity { get; set; }
        [StringLength(250)]
        public string Observations { get; set; }
        [Required]
        [StringLength(20)]
        public string ProjectNumber { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductType { get; set; }
        [StringLength(250)]
        public string ProductDescription { get; set; }
        [Required]
        [StringLength(20)]
        public string ProductCode { get; set; }
        [Required]
        [StringLength(50)]
        public string ProductModel { get; set; }
    }
}