// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class ArticlesView
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }
        [Required]
        [StringLength(20)]
        public string Unit { get; set; }
        [StringLength(100)]
        public string TradeMark { get; set; }
        [StringLength(100)]
        public string Model { get; set; }
        public int FamilyId { get; set; }
        [Required]
        [StringLength(100)]
        public string FamilyName { get; set; }
        public int GroupId { get; set; }
        [Required]
        [StringLength(50)]
        public string GroupName { get; set; }
        [Required]
        [StringLength(60)]
        public string Code { get; set; }
        [StringLength(200)]
        public string Observations { get; set; }
    }
}