// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Index(nameof(PurchaseOrderId), Name = "FK_ArticlesToPurchase_PurchaseOrders")]
    public partial class ArticlesToPurchase
    {
        [Key]
        public int QuoteId { get; set; }
        [Key]
        public int PurchaseOrderId { get; set; }
        public int Quantity { get; set; }
        public DateTime? ReceptionDate { get; set; }
        public DateTime? DepartureDate { get; set; }
        public float SalePrice { get; set; }

        [ForeignKey(nameof(PurchaseOrderId))]
        [InverseProperty(nameof(PurchaseOrders.ArticlesToPurchase))]
        public virtual PurchaseOrders PurchaseOrder { get; set; }
        [ForeignKey(nameof(QuoteId))]
        [InverseProperty(nameof(Quotes.ArticlesToPurchase))]
        public virtual Quotes Quote { get; set; }
    }
}