// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class ArticlesToPurchaseView
    {
        public int QuoteId { get; set; }
        public int PurchaseOrderId { get; set; }
        public int Quantity { get; set; }
        public DateTime? ReceptionDate { get; set; }
        public DateTime? DepartureDate { get; set; }
        public float SalePrice { get; set; }
        public int GroupId { get; set; }
        [Required]
        [StringLength(50)]
        public string GroupName { get; set; }
        public int FamilyId { get; set; }
        [Required]
        [StringLength(30)]
        public string FamilyName { get; set; }
        public int ArticleId { get; set; }
        [Required]
        [StringLength(50)]
        public string ArticleName { get; set; }
        [Required]
        [StringLength(62)]
        public string ArticleCode { get; set; }
        [StringLength(50)]
        public string TradeMark { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [StringLength(50)]
        public string SKU { get; set; }
        [Required]
        [StringLength(20)]
        public string Unit { get; set; }
        public DateTime QuoteDate { get; set; }
        [Required]
        [StringLength(5)]
        public string Currency { get; set; }
    }
}