// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    public partial class ArticleGroups
    {
        public ArticleGroups()
        {
            ArticleFamilies = new HashSet<ArticleFamilies>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }
        [Required]
        [StringLength(20)]
        public string Code { get; set; }
        public short HasVariablePrice { get; set; }

        [InverseProperty("Group")]
        public virtual ICollection<ArticleFamilies> ArticleFamilies { get; set; }
    }
}