// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    public partial class Contacts
    {
        public Contacts()
        {
            ClientContacts = new HashSet<ClientContacts>();
            ProviderContacts = new HashSet<ProviderContacts>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string FullName { get; set; }
        [StringLength(50)]
        public string EmailAddress { get; set; }
        [Required]
        [StringLength(20)]
        public string MobilePhone { get; set; }
        [StringLength(50)]
        public string Position { get; set; }

        [InverseProperty("Contact")]
        public virtual ICollection<ClientContacts> ClientContacts { get; set; }
        [InverseProperty("Contact")]
        public virtual ICollection<ProviderContacts> ProviderContacts { get; set; }
    }
}