// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Index(nameof(Use), Name = "IX_Keys_Use")]
    public partial class Keys
    {
        [Key]
        public string Id { get; set; }
        public int Version { get; set; }
        public DateTime Created { get; set; }
        public string Use { get; set; }
        [Required]
        [StringLength(100)]
        public string Algorithm { get; set; }
        public bool IsX509Certificate { get; set; }
        public bool DataProtected { get; set; }
        [Required]
        public string Data { get; set; }
    }
}