// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    public partial class PersonInformation
    {
        [Key]
        public int Id { get; set; }
        [StringLength(450)]
        public string AspNetUserId { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string MiddleName { get; set; }
        [Required]
        [StringLength(50)]
        public string FatherSurname { get; set; }
        [Required]
        [StringLength(50)]
        public string MotherSurname { get; set; }
        public DateTime? BirthDate { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
    }
}