// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    public partial class Providers
    {
        public Providers()
        {
            ProviderContacts = new HashSet<ProviderContacts>();
            PurchaseOrders = new HashSet<PurchaseOrders>();
            Quotes = new HashSet<Quotes>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string MarketName { get; set; }
        [Required]
        [StringLength(50)]
        public string LegalName { get; set; }
        [Required]
        [StringLength(50)]
        public string FiscalAddress { get; set; }
        [Required]
        [StringLength(50)]
        public string City { get; set; }
        [Required]
        [StringLength(50)]
        public string Province { get; set; }
        [Required]
        [StringLength(50)]
        public string Country { get; set; }
        [Required]
        [StringLength(50)]
        public string PostalCode { get; set; }
        [Required]
        [StringLength(20)]
        public string PhoneNumber { get; set; }
        [Required]
        [StringLength(50)]
        public string Website { get; set; }
        [Required]
        [StringLength(50)]
        public string TypeOfPayment { get; set; }
        [Required]
        [StringLength(50)]
        public string PaymentCondition { get; set; }
        [StringLength(50)]
        public string CreditLimit { get; set; }
        public double Discount { get; set; }
        public short HomeDelivery { get; set; }
        public string Observations { get; set; }
        public short HasTaxes { get; set; }

        [InverseProperty("Provider")]
        public virtual ICollection<ProviderContacts> ProviderContacts { get; set; }
        [InverseProperty("Provider")]
        public virtual ICollection<PurchaseOrders> PurchaseOrders { get; set; }
        [InverseProperty("Provider")]
        public virtual ICollection<Quotes> Quotes { get; set; }
    }
}