// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class PurchaseOrdersView
    {
        public int Id { get; set; }
        public DateTime? IssuedDate { get; set; }
        public DateTime? DeliveryDate { get; set; }
        [Required]
        [StringLength(10)]
        public string Currency { get; set; }
        public double Discount { get; set; }
        [Required]
        [StringLength(50)]
        public string Status { get; set; }
        public DateTime? ReceptionDate { get; set; }
        [StringLength(50)]
        public string InvoiceNumber { get; set; }
        public string Observations { get; set; }
        [StringLength(50)]
        public string OrderNumber { get; set; }
        public int ProviderId { get; set; }
        [Required]
        [StringLength(50)]
        public string ProviderLegalName { get; set; }
        public short HasTaxes { get; set; }
        public int ProjectId { get; set; }
        [StringLength(20)]
        public string ProjectNumber { get; set; }
        public int ClientId { get; set; }
        [Required]
        [StringLength(50)]
        public string ClientMarketName { get; set; }
        public int? RequisitionId { get; set; }
        [StringLength(50)]
        public string RequisitionNumber { get; set; }
    }
}