// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class QuotesView
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        [StringLength(50)]
        public string SKU { get; set; }
        public float Price { get; set; }
        [Required]
        [StringLength(5)]
        public string Currency { get; set; }
        public DateTime DateUpdated { get; set; }
        public int ProviderId { get; set; }
        [Required]
        [StringLength(50)]
        public string ProviderMarketName { get; set; }
        [Required]
        [StringLength(50)]
        public string ProviderLegalName { get; set; }
        public float ProviderDiscount { get; set; }
        [Required]
        [StringLength(50)]
        public string ArticleName { get; set; }
        [Required]
        [StringLength(250)]
        public string ArticleDescription { get; set; }
        [StringLength(50)]
        public string TradeMark { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [Required]
        [StringLength(20)]
        public string Unit { get; set; }
        public int GroupId { get; set; }
        [Required]
        [StringLength(50)]
        public string GroupName { get; set; }
        public int FamilyId { get; set; }
        [Required]
        [StringLength(30)]
        public string FamilyName { get; set; }
        [Required]
        [StringLength(62)]
        public string ArticleCode { get; set; }
        public bool MustQuoteDaily { get; set; }
    }
}