// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class RequisitionArticlesView
    {
        public int RequisitionId { get; set; }
        [Required]
        [StringLength(50)]
        public string RequisitionNumber { get; set; }
        public int ArticleId { get; set; }
        [Required]
        [StringLength(50)]
        public string ArticleName { get; set; }
        public int GroupId { get; set; }
        [Required]
        [StringLength(30)]
        public string GroupName { get; set; }
        public int FamilyId { get; set; }
        [Required]
        [StringLength(30)]
        public string FamilyName { get; set; }
        [Required]
        [StringLength(62)]
        public string ArticleCode { get; set; }
        public int ProjectId { get; set; }
        [StringLength(20)]
        public string ProjectNumber { get; set; }
        public int Quantity { get; set; }
        public DateTime? RequiredDate { get; set; }
    }
}