// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCPackServer.Entities
{
    [Keyless]
    public partial class RequisitionsView
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string RequisitionNumber { get; set; }
        public DateTime? RequiredDate { get; set; }
        public DateTime? IssuedDate { get; set; }
        [Required]
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        [Required]
        [StringLength(101)]
        public string UserShortName { get; set; }
    }
}